config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
    path('',include('src.applications.foro.urls'))
]

src/applications/foro/urls.py
from django.urls import path
from src.applications.foro.views.viewComment import ListComments
from src.applications.foro.views.createComment import CreateComment
app_name = 'foro'
urlpatterns = [
    path('', ListComments.as_view(), name='home'),
    path('create/', CreateComment, name='createComment'),
]

src/applications/foro/models/comment.py
from django.db import models
class Comment(models.Model):
    """
    Represents a comment on a post in the forum.
    """

    name_user = models.CharField(max_length=255)
    title_post = models.CharField(max_length=255)
    description_post = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        """
        This class provides metadata options for the Comment model.
        """
        app_label = 'foro'

    def __str__(self):
        """
        Returns a string representation of the Comment object.
        
        The string representation is the name of the user who made the comment.
        
        Returns:
            str: The name of the user who made the comment.
        """
        return str(self.name_user)
    

src/applications/foro/views/createComment.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from src.applications.foro.models.comment import Comment
def CreateComment(request):
    """
    Create a new comment.

    Args:
        request: The HTTP request object.

    Returns:
        If the request method is 'POST', creates a new comment with the provided data and redirects to the home page.
        If the request method is not 'POST', renders the 'create_comment.html' template.

    """
    if request.method == 'POST':
        name_user = request.POST.get('name_user')
        title_post = request.POST.get('title_post')
        description_post = request.POST.get('description_post')
        nuevo_post = Comment.objects.create(
            name_user=name_user,
            title_post=title_post,
            description_post=description_post
        )
        nuevo_post.save()
        return redirect(reverse_lazy('foro:home'))
    else:
        return render(request, 'foro/create_comment.html')
    

src/applications/foro/views/viewComment.py
from django.views.generic import ListView
from src.applications.foro.models.comment import Comment

class ListComments(ListView):
    """
    A view for listing comments.

    This view extends the Django ListView class and is used to display a list of comments.
    It retrieves the comments from the database and filters them based on a search query if provided.

    Attributes:
        model (Model): The model class representing the comments.
        template_name (str): The name of the template used to render the view.
        context_object_name (str): The name of the variable used to store the comments in the template context.
    """

    model = Comment
    template_name = "foro/home.html"
    context_object_name = 'list_elements'

    def get_queryset(self):
        """
        Get the queryset of comments.

        This method is called to retrieve the comments from the database.
        If a search query is provided in the request parameters, it filters the comments based on the query.
        Otherwise, it returns all the comments.

        Returns:
            QuerySet: The queryset of comments.
        """
        query = self.request.GET.get('text')
        if query:
            return Comment.objects.filter(name_user__icontains=query)
        else:
            return Comment.objects.all()

src/user_interface/templates/foro/create_comment.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Crear comentario</title>
    <link href="{%static 'CSS/foro/create_comment.css'%}" rel="stylesheet" />
  </head>
  <body>
    <div class="container">
      <div class="form-container">
        <form class="form" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="email">Nombre</label>
            <input required="" name="name_user" id="name_user" type="text" />
          </div>
          <div class="form-group">
            <label for="">Título</label>
            <input required="" name="title_post" id="title_post" type="text" />
          </div>
          <div class="form-group">
            <label for="textarea">Descripción</label>
            <textarea
              required=""
              cols="50"
              rows="10"
              id="description_post"
              name="description_post"
            ></textarea>
          </div>
          <button type="submit" class="form-submit-btn">Crear</button>
        </form>
      </div>
    </div>
  </body>
</html>

src/user_interface/templates/foro/home.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Colombia en el ámbito internaiconal</title>
    <link href="{%static 'CSS/foro/home.css'%}" rel="stylesheet" />
  </head>
  <body>
    <div class="container">
      <div class="container-info">
        <div class="card">
          <div class="circle"></div>
          <div class="circle"></div>
          <div class="card-inner">
            <h1>Colombia en el ámbito internacional</h1>
          </div>
        </div>
        <div class="container-relevant-info">
          <div class="left-container">
            <div class="e-card playing">
              <div class="image"></div>

              <div class="wave"></div>
              <div class="wave"></div>
              <div class="wave"></div>

              <div class="infotop">
                <h2>
                  Espacio de reflexiones para Colombia el ámbito internacional
                </h2>
                <br />
                <div class="name">Kristian Restrepo Osorio</div>
              </div>
            </div>
            <button>
              <a href="{% url 'foro:createComment'%}" class="btn2"
                ><span class="spn2">CREAR COMENTARIO</span></a
              >
            </button>
          </div>
          <div class="right-container">
            <div class="title-reflection"><h2>REFLEXIONES</h2></div>
            <form method="GET">
              <div class="input-group">
                <input
                  required=""
                  type="text"
                  name="text"
                  autocomplete="off"
                  class="input"
                />
                <label class="user-label">Nombre de estudiante</label>
              </div>
            </form>
            <div class="card-comment-container">
              {% for element in list_elements %}
              <div class="card-comment">
                <div class="body">
                  <h2>{{element.title_post}}</h2>
                  <span class="username">De: {{element.name_user}}</span>
                  <br />
                  <p class="text">{{element.description_post}}</p>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>